galaxy_info:
  author: Rostow GOKENg
  description: Install the latest version of ChromeDriver
  company: Rostow Company Ltd
  license: license (GPL-2.0-or-later, MIT, etc)
  min_ansible_version: 2.4
  platforms:
    - name: Debian
      versions:
      - jessie
    - name: Ubuntu
      versions:
      - trusty
      - xenial
  galaxy_tags:
    - Chromedriver  
